// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuvLKGqhP-9w4pGQTyAn7jNtbq-b96ZiE',
    appId: '1:186654884711:web:07d2b70d66ee49dad265c2',
    messagingSenderId: '186654884711',
    projectId: 'elvan-870ae',
    authDomain: 'elvan-870ae.firebaseapp.com',
    storageBucket: 'elvan-870ae.appspot.com',
    measurementId: 'G-HNM2BBPH51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQDZ2NVS3WNb_wvrpdyi_MuhC4xFpt9dg',
    appId: '1:186654884711:android:7015ff1b70e58043d265c2',
    messagingSenderId: '186654884711',
    projectId: 'elvan-870ae',
    storageBucket: 'elvan-870ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1yTSXRjcU_NObXVnAgrNYwXPY6fxJh8',
    appId: '1:186654884711:ios:09cb46e5a713ebe9d265c2',
    messagingSenderId: '186654884711',
    projectId: 'elvan-870ae',
    storageBucket: 'elvan-870ae.appspot.com',
    androidClientId: '186654884711-qs3mt2m5qrocg5e5veie4tj3tadffabj.apps.googleusercontent.com',
    iosClientId: '186654884711-ju30q6be5tn8t49sfto9a0j98fgih9b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.elvan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn1yTSXRjcU_NObXVnAgrNYwXPY6fxJh8',
    appId: '1:186654884711:ios:09cb46e5a713ebe9d265c2',
    messagingSenderId: '186654884711',
    projectId: 'elvan-870ae',
    storageBucket: 'elvan-870ae.appspot.com',
    androidClientId: '186654884711-qs3mt2m5qrocg5e5veie4tj3tadffabj.apps.googleusercontent.com',
    iosClientId: '186654884711-ju30q6be5tn8t49sfto9a0j98fgih9b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.elvan',
  );
}
